Github Action for Workflow Build Packer

diff --git a/.github/workflows/packer-build.yml b/.github/workflows/packer-build.yml
--- a/.github/workflows/packer-build.yml
+++ b/.github/workflows/packer-build.yml
@@ -154,22 +154,24 @@ jobs:
     - name: Share the AMI and Save AMI_ID
       id: share_ami
       run: |
-          AMI_ID=$(aws ec2 describe-images \
-              --owners self \
-              --filters "Name=state,Values=available" \
-              --query "Images | sort_by(@, &CreationDate)[-1].ImageId" \
-              --output text)
+         AWS_REGION="us-east-1"  
+         AMI_ID=$(aws ec2 describe-images \
+         --owners self \
+         --filters "Name=state,Values=available" \
+         --query "Images | sort_by(@, &CreationDate)[-1].ImageId" \
+         --output text --region "$AWS_REGION")
 
-          if [ -n "$AMI_ID" ]; then
-            echo "Sharing AMI $AMI_ID with DEMO account..."
-            aws ec2 modify-image-attribute --image-id "$AMI_ID" \
-              --launch-permission "{\"Add\": [{\"UserId\": \"${{ secrets.DEMO_USER }}\"}]}"
-            echo "::set-output name=ami_id::$AMI_ID"
-            echo "$AMI_ID" > ami_id.txt
-          else
-            echo "AMI not found, exiting."
-            exit 1
-          fi
+         if [ -n "$AMI_ID" ]; then
+         echo "Sharing AMI $AMI_ID with DEMO account..."
+         aws ec2 modify-image-attribute --image-id "$AMI_ID" \
+         --launch-permission "{\"Add\": [{\"UserId\": \"***\"}]}" --region "$AWS_REGION"
+         echo "::set-output name=ami_id::$AMI_ID"
+         echo "$AMI_ID" > ami_id.txt
+         else
+         echo "AMI not found, exiting."
+         exit 1
+         fi
+
 
     - name: Upload AMI_ID Artifact
       uses: actions/upload-artifact@v4
